# Generated by Django 3.2.6 on 2021-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardproperty',
            name='pin_addr',
        ),
        migrations.AddField(
            model_name='boardproperty',
            name='node_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardproperty',
            name='mac_addr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
