# Generated by Django 3.2.6 on 2021-09-12 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210912_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedata',
            name='board',
        ),
        migrations.RemoveField(
            model_name='livedata',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='board',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='counter',
        ),
        migrations.AddField(
            model_name='livedata',
            name='data',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livedata',
            name='mac_addr',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='data',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='mac_addr',
            field=models.CharField(default=111111, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoardProperty',
        ),
    ]
