# Generated by Django 3.2.6 on 2021-09-13 05:12

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20210912_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='mac_addr',
            field=models.CharField(max_length=100),
        ),
    ]
