# Generated by Django 3.2.6 on 2021-09-15 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_logdata_mac_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='pin',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='livedata',
            name='unixTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logdata',
            name='pin',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='logdata',
            name='unixTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livedata',
            name='mac_addr',
            field=models.CharField(max_length=100),
        ),
    ]
