# Generated by Django 3.2.6 on 2021-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20210915_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='diff_data',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logdata',
            name='diff_data',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='pin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
