# Generated by Django 3.2.6 on 2021-10-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20210930_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livedata',
            old_name='unixTime',
            new_name='sendDataTime',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='unixTime',
            new_name='sendDataTime',
        ),
    ]
